import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import { cn } from '@/lib/utils';

import './globals.css';
import { QueryProviders } from '@/components/providers/queryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Jira',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(cn(inter.className), 'antialiased min-h-screen')}>
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
